image: python:3.11.2
pipelines:
  default:
    - step:
        script:
          - echo "hello world!"
  branches:
    master:
      - step:  
          script:
            - ssh ubuntu@157.241.54.34 /home/ubuntu/Eris-saleh/Frontend/eris-saleh/devCdScript.sh 
